### ISSUE TITLE
[Bug] the dataset is not auto downloaded.

### ISSUE THREAD

**Issue by amulil** [InternLM/xtuner#112]
When I run ` NPROC_PER_NODE=8 xtuner train llama2_7b_qlora_moss_sft_all_e2_gpu8`, the dataset is not auto downloaded.

I need to mkdir `./data/` and down load dataset `moss-003-sft-no-tools.jsonl` by hand.

**Comment by LZHgrla** [comment]
Hi @amulil , you are right!

Because using `dataset = load_dataset("fnlp/moss-003-sft-data")` directly will result in an error, download MOSS-003-SFT dataset by hands is required

Related commands can be found on [docs](https://github.com/InternLM/xtuner/blob/main/docs/en/user_guides/dataset_prepare.md#moss-003-sft).
