### ISSUE TITLE
LLaVA how to replace qwen LLM model？

### ISSUE THREAD

**Issue by PCIResearch** [InternLM/xtuner#292]
Hello, may I know how to replace the qwen model in the LLM module of llava? I have tried to replace it, but I encountered many error issues. For example, the bos_token_id is not defined. Could you provide a tutorial or guidance on how to replace the qwen model?

**Comment by LZHgrla** [comment]
qwen model is so different from other LLMs, since its tokenizer does not have `bos_token_id`. However, `transformers` requires `bos_token_id` when using `inputs_embeds` as inputs (LLaVA needs this feature).

A quick solution is to configure the tokenizer as follows
```python
# For chat model
tokenizer = dict(
    type=AutoTokenizer.from_pretrained,
    pretrained_model_name_or_path=llm_name_or_path,
    trust_remote_code=True,
    padding_side='right',
    bos_token='<|im_start|>',
    eos_token='<|im_end|>')
```
This is just a temporary solution, the correct solution is to support `bos_token` from the upstream qwen model.

Meanwhile, please do not forget to modify `EvaluateChatHook`'s `stop_word` as 
https://github.com/InternLM/xtuner/blob/5962cc87d2893870f5ccdd112a3adfe3883fb14d/xtuner/configs/qwen/qwen_7b_chat/qwen_7b_chat_qlora_alpaca_e3.py#L152

**Comment by PCIResearch** [comment]
> qwen model is so different from other LLMs, since its tokenizer does not have `bos_token_id`. However, `transformers` requires `bos_token_id` when using `inputs_embeds` as inputs (LLaVA needs this feature).
> 
> A quick solution is to configure the tokenizer as follows
> 
> ```python
> # For chat model
> tokenizer = dict(
>     type=AutoTokenizer.from_pretrained,
>     pretrained_model_name_or_path=llm_name_or_path,
>     trust_remote_code=True,
>     padding_side='right',
>     bos_token='<|im_start|>',
>     eos_token='<|im_end|>')
> ```
> 
> This is just a temporary solution, the correct solution is to support `bos_token` from the upstream qwen model.
> 
> Meanwhile, please do not forget to modify `EvaluateChatHook`'s `stop_word` as
> 
> https://github.com/InternLM/xtuner/blob/5962cc87d2893870f5ccdd112a3adfe3883fb14d/xtuner/configs/qwen/qwen_7b_chat/qwen_7b_chat_qlora_alpaca_e3.py#L152

Yes, I tried the same thing yesterday and it's working fine so far.

**Comment by thomas-yanxin** [comment]
请问经过Qwen-7B-Chat微调的LLaVA，如何使用xtuner chat进行对话？

顺利微调，但是chat的时候出现如下报错：
![image](https://github.com/InternLM/xtuner/assets/58030051/14a46dcc-37af-4b56-9915-da500aa89089)

**Comment by LZHgrla** [comment]
@thomas-yanxin 
`transformers`的模型在使用`generate()`，并传入`inputs_embeds`，而非`input_ids`时，必须确保传入 `bos_token_id`。而 qwen 模型 `bos_token_id` 为 `None`，进而会报这个错。

因此问题出在 qwen 模型的实现上，其不支持 `inputs_embeds`-only 的 generate 输入。

**Comment by Yanllan** [comment]
I have trained on qwen and got.iter_xtuner, how do I convert it to offical_llava format
