### ISSUE TITLE
two 8 A100 Server have a slower speed than one 8 A100 Server 

### ISSUE THREAD

**Issue by jjjkkyz** [InternLM/xtuner#310]
I am training mixtral-8x7B lora.
Now I have another 8 A100 machine, but training on two machine do not have a faster speed than one machine.
In details, two 8 A100 Server need 6 hours, and one machine only need 5 hours.
Any idea to speed up traning speed on two machine? Should I change some parameters in config file？

**Comment by jjjkkyz** [comment]
I found that in machine with rank=1, log stop printing before training loop and rank=0 machine continue to start training loop. GPU in rank 1 machine is full used but no traning. Maybe I should turn on some flag to see deeper log?

**Comment by LZHgrla** [comment]
If both two nodes are idle, it usually won't be slower unless the cost of communication between nodes is high. Modifying the config can't solve this problem because this is often a hardware linking issue.

As for the log, it will only appear on the rank0 gpu of the rank0 machine, so I think this is normal.

**Comment by jjjkkyz** [comment]
> If both two nodes are idle, it usually won't be slower unless the cost of communication between nodes is high. Modifying the config can't solve this problem because this is often a hardware linking issue.
> 
> As for the log, it will only appear on the rank0 gpu of the rank0 machine, so I think this is n
