### ISSUE TITLE
InternLM2Converter requires the protobuf library but it was not found in your environment.

### ISSUE THREAD

**Issue by yiyexy** [InternLM/xtuner#356]
I met follow error, when I merge llm-7b adapter.

<img width="959" alt="image" src="https://github.com/InternLM/xtuner/assets/35927125/b16fc327-baac-4651-8a1f-a07ae8ac1f20">

But I previously successfully merged llm-20b.

**Comment by yiyexy** [comment]
The problem had be solved after ` pip install protobuf`. But I still want to know the reason.

**Comment by LZHgrla** [comment]
`protobuf` is required by other thrid-party library (e.g., `transformers`) in some cases.

In my option, the version management of these libraries should be placed in the upstream repository, not in the `xtuner`.

Nevertheless, thanks again for reporting this issue!

**Comment by hellocrystal** [comment]
socket.timeout: timed out
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /internlm/internlm2_5-7b-chat/resolve/main/tf_model.h5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028E2CDC3340>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /internlm/internlm2_5-7b-chat/resolve/main/tf_model.h5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028E2CDC3340>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: c12744c4-670d-4484-9d02-d7f8ff417168)')

**Comment by hellocrystal** [comment]
socket.timeout: timed out
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /internlm/internlm2_5-7b-chat/resolve/main/tf_model.h5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028E2CDC3340>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /internlm/internlm2_5-7b-chat/resolve/main/tf_model.h5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028E2CDC3340>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: c12744c4-670d-4484-9d02-d7f8ff417168)')
