### ISSUE TITLE
Do you have plan of adding RWKV finetuning?

### ISSUE THREAD

**Issue by StarCycle** [InternLM/xtuner#417]
Hello,

Do you have plan to integrate [RWKV](https://github.com/BlinkDL/RWKV-LM), which should be super fast on embedded devices?

Best,
Zhuoheng

**Comment by LZHgrla** [comment]
@StarCycle  Hi!

I think that xtuner has already supported the fine-tuning of RWKV (but we do not test it), because `transformers` supports the RwkvForCausalLM models(https://github.com/huggingface/transformers/blob/main/src/transformers/models/rwkv/modeling_rwkv.py)

Maybe you can have a try. Feel free to contact me if there is any progress.

**Comment by StarCycle** [comment]
Great thanks!
